const types = {
    STUDENT_START:'STUDENT_START',
    SET_CUR_STUDENT:'SET_CUR_STUDENT',
    STUDENT_FAIL:'STUDENT_FAIL',
    REMOVE_ERROR_STUDENT:'REMOVE_ERROR_STUDENT',
    POP_UP_STUDENT:'POP_UP_STUDENT'
}

export default types;