const types = {
    MENTOR_START:'MENTOR_START',
    SET_CUR_MENTOR:'SET_CUR_MENTOR',
    MENTOR_FAIL:'MENTOR_FAIL',
    REMOVE_ERROR_MENTOR:'REMOVE_ERROR_MENTOR',
    POP_UP_MENTOR:'POP_UP_MENTOR'
}

export default types;