module.exports.auth = require('./auth')
module.exports.demands = require('./demands')
module.exports.event = require('./event')
module.exports.mentor = require('./mentor')
module.exports.student = require('./student')
module.exports.room= require('./room')